### ISSUE TITLE
disconnect slot using function instead of connection class

### ISSUE THREAD

**Issue by christophe-f8** [fr00b0/nod#17]
Hi,

I'm trying to find a way to disconnect a slot without having to store its connection class.
I tried many different things but never could write compilable code.

What I'm trying to do is the following:

// connection, as usual (in the case the slot has one parameter), but without storing the connection class
signal.connect(std::bind(&Foo::bar, this, std::placeholders::_1));

// disconnection, without using the connection class
// could be like this
signal.connect(std::bind(&Foo::bar, this, std::placeholders::_1));
// or like this (I won't have several connections from a single signal to multiple slots within my object)
signal.connect(this);

Is this achievable somehow ?

**Comment by fr00b0** [comment]
Hello,
First off, I apologize for the late response.

What you wan't to do is not possible with the `nod` library. Internally the signals are using `std::function` objects to hold the connected slots, and the standard library does not provide any way of comparing instances of `std::function` for equality. The provided `operator==´ can only compare equal against `nullptr`. This makes implementing what you want a hard problem without resorting to implementation specific solutions.

If I may ask. What is your use case? What is the issue with holding on to your `connection` instances that is returned when connecting your slots?

**Comment by fr00b0** [comment]
I will not implement similar functionality, but I'm glad you managed to work around the issue in your code base. The Qt signal/slot stuff relies a bit to much on the `Q_OBJECT` and meta object compiler to be a viable comparison to `nod` (which tries to be a more generic solution for signal/slot)

I'll close this issue now, but feel free to reopen if you need to.
